name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Se ejecuta solo cuando hay cambios en la rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el c칩digo fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker Buildx (para construir im치genes Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Iniciar sesi칩n en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y subir la imagen a Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # Directorio actual donde est치 el Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crud-imagenes:latest
